version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
  cache:
    image: redis:6.2-alpine
    restart: always
    environment:
     REDIS_PASSWORD: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
